const CONFIG = {
  PANEL_SPREADSHEET_ID: 'USE_YOUR_OWN_PANEL_SPREADSHEET_ID_HERE',
  INVOICE_TEMPLATE_ID: 'USE_YOUR_OWN_INVOICE_TEMPLATE_ID_HERE',
  INVOICES_FOLDER_ID: 'USE_YOUR_OWN_INVOICES_FOLDER_ID_HERE',
};
